//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nba
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Picture
    {
        public int Id { get; set; }
        public string Img { get; set; }
        public string Description { get; set; }
        public Nullable<int> NumberOfLike { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
