//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nba
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.MatchupLogs = new ObservableCollection<MatchupLog>();
            this.PlayerInTeams = new ObservableCollection<PlayerInTeam>();
            this.PlayerStatistics = new ObservableCollection<PlayerStatistic>();
        }
    
        public int PlayerId { get; set; }
        public string Name { get; set; }
        public int PositionId { get; set; }
        public System.DateTime JoinYear { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string College { get; set; }
        public string CountryCode { get; set; }
        public string Img { get; set; }
        public bool IsRetirment { get; set; }
        public Nullable<System.DateTime> RetirmentTime { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<MatchupLog> MatchupLogs { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<PlayerInTeam> PlayerInTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<PlayerStatistic> PlayerStatistics { get; set; }
    }
}
